import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
/**
 * @author Isabel Ramirez
 * @created 8.13.26
 */

public class CartCheckoutTestDatabase {

    public static Connection createConnection()
            throws SQLException {

        Connection connection =
                DriverManager.getConnection(
                        "jdbc:h2:mem:cart_checkout_test"
                );

        createTables(connection);

        return connection;
    }

    private static void createTables(Connection connection)
            throws SQLException {

        try (Statement statement =
                     connection.createStatement()) {

            statement.execute("""
                    CREATE TABLE users (
                        user_id INTEGER
                            GENERATED BY DEFAULT AS IDENTITY
                            PRIMARY KEY,
                        username VARCHAR(100) NOT NULL UNIQUE,
                        password_hash VARCHAR(255) NOT NULL,
                        email VARCHAR(255) NOT NULL UNIQUE,
                        is_active INTEGER NOT NULL DEFAULT 1            
                    )
                    """);

            statement.execute("""
                    CREATE TABLE products (
                        product_id INTEGER
                            GENERATED BY DEFAULT AS IDENTITY
                            PRIMARY KEY,
                        product_name VARCHAR(255) NOT NULL,
                        price DECIMAL(10, 2) NOT NULL,
                        stock_quantity INTEGER NOT NULL
                    )
                    """);

            statement.execute("""
        CREATE TABLE carts (
            cart_id INTEGER
                GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,
            user_id INTEGER NOT NULL,
            status VARCHAR(20) NOT NULL
                DEFAULT 'ACTIVE',
            created_at TIMESTAMP
                DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP
                DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id)
                REFERENCES users(user_id)
        )
        """);

            statement.execute("""
                    CREATE TABLE cart_items (
                        cart_item_id INTEGER
                            GENERATED BY DEFAULT AS IDENTITY
                            PRIMARY KEY,
                        cart_id INTEGER NOT NULL,
                        product_id INTEGER NOT NULL,
                        quantity INTEGER NOT NULL,
                        unit_price DECIMAL(10, 2) NOT NULL,
                        UNIQUE (cart_id, product_id),
                        FOREIGN KEY (cart_id)
                            REFERENCES carts(cart_id),
                        FOREIGN KEY (product_id)
                            REFERENCES products(product_id)
                    )
                    """);

            statement.execute("""
                    CREATE TABLE orders (
                        order_id INTEGER
                            GENERATED BY DEFAULT AS IDENTITY
                            PRIMARY KEY,
                        user_id INTEGER NOT NULL,
                        total_amount DECIMAL(10, 2) NOT NULL,
                        status VARCHAR(20) NOT NULL
                            DEFAULT 'PENDING',
                        created_at TIMESTAMP
                            DEFAULT CURRENT_TIMESTAMP,
                        FOREIGN KEY (user_id)
                            REFERENCES users(user_id)
                    )
                    """);

            statement.execute("""
                    CREATE TABLE order_items (
                        order_item_id INTEGER
                            GENERATED BY DEFAULT AS IDENTITY
                            PRIMARY KEY,
                        order_id INTEGER NOT NULL,
                        product_id INTEGER NOT NULL,
                        quantity INTEGER NOT NULL,
                        unit_price DECIMAL(10, 2) NOT NULL,
                        FOREIGN KEY (order_id)
                            REFERENCES orders(order_id),
                        FOREIGN KEY (product_id)
                            REFERENCES products(product_id)
                    )
                    """);
        }
    }
}
