import static org.testfx.api.FxAssert.verifyThat;

import java.io.File;
import javafx.stage.Stage;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.testfx.framework.junit5.ApplicationTest;
import org.testfx.matcher.base.NodeMatchers;

/**
 * UI Integration tests using TestFX for the Login scene workflow.
 *
 * @author Miguel Quezada
 * @version 0.1.0
 * @since 2026-08-13
 *
 *  These TestFX unit tests were generated by Courtesy of Claude from Anthropic.
 *  Prompt Used:
 *  I have these code files ( submitted the code )
 * src/main/java/AdminController.java
 * src/main/java/DatabaseManager.java
 * src/main/java/Main.java
 * src/main/java/SceneFactory.java
 * src/main/java/SceneType.java
 * src/main/java/UserInfo.java
 *  Write TestFX UI tests for Login Controller, verifying login clicks and navigation.
 *  The tests will live in this folder in my project
 *  src/test/java/
 *
 */
public class LoginSceneTest extends ApplicationTest {

  private DatabaseManager db;
  private Stage primaryStage;
  private static final String TEST_DB_FILE = "app.db";

  /**
   * Initializes and stores the primary stage instance provided by TestFX.
   *
   * @param stage the primary JavaFX stage allocated for testing
   */
  @Override
  public void start(Stage stage) {
    this.primaryStage = stage;
  }

  /**
   * Sets up the test environment before each test method runs. Ensures any residual
   * database file is cleaned up, establishes a fresh {@link DatabaseManager} instance,
   * populates test user accounts, and launches the login scene on the JavaFX thread.
   *
   * @throws Exception if an error occurs during database setup or scene initialization
   */
  @BeforeEach
  public void setUp() throws Exception {
    // 1. Delete old test DB file if present
    File testDb = new File(TEST_DB_FILE);
    if (testDb.exists()) {
      testDb.delete();
    }

    // 2. Initialize fresh DatabaseManager instance
    db = new DatabaseManager();

    // 3. Seed fresh test users before every single test
    seedTestUsers();

    // 4. Launch initial LOGIN scene on the FX Thread
    interact(() -> {
      primaryStage.setTitle("Cache Me Outside Clothing Co. - Test");
      primaryStage.setScene(SceneFactory.create(SceneType.LOGIN, primaryStage, db));
      primaryStage.show();
    });
  }

  /**
   * Cleans up resources after each test method completes. Closes the database connection,
   * invokes garbage collection to release SQLite file handles, and removes the temporary database.
   *
   * @throws Exception if an error occurs while releasing database resources
   */
  @AfterEach
  public void tearDown() throws Exception {
    if (db != null) {
      db.close();
      db = null;
    }
    // Force garbage collection to release SQLite file handles on Windows
    System.gc();

    File testDb = new File(TEST_DB_FILE);
    if (testDb.exists()) {
      testDb.delete();
    }
  }

  /**
   * Seeds initial test records into the DatabaseManager instance.
   */
  private void seedTestUsers() {
    db.getUserDAO().registerUser(
        "john_doe",
        "Password123!",
        "john@example.com",
        "John",
        "Doe",
        "555-0199",
        "123 Main St",
        "Fresno",
        "CA",
        "93720",
        "USER",
        "What was the mascot of your first school?",
        "Bulldogs"
    );

    db.getUserDAO().registerUser(
        "admin_user",
        "AdminPass123!",
        "admin@example.com",
        "Admin",
        "User",
        "555-0100",
        "456 Admin Ave",
        "Clovis",
        "CA",
        "93611",
        "ADMIN",
        "What is your mother's maiden name?",
        "Smith"
    );
  }

  /**
   * Verifies that submitting the login form with empty input fields displays
   * the appropriate client-side validation error message to the user.
   */
  @Test
  @DisplayName("Should show validation error when logging in with empty credentials")
  public void testEmptyCredentialsValidation() {
    clickOn("Login");
    verifyThat("Username and Password are required.", NodeMatchers.isVisible());
  }

  /**
   * Verifies that entering unrecognized or invalid login credentials displays
   * an authentication failure message and keeps the user on the login scene.
   */
  @Test
  @DisplayName("Should display error status message when given invalid credentials")
  public void testInvalidLoginCredentials() {
    clickOn("#usernameField").eraseText(20).write("invalid_user");
    clickOn("#passwordField").eraseText(20).write("wrong_password");
    clickOn("#loginButton");

    verifyThat("Invalid username or password.", NodeMatchers.isVisible());
  }

  /**
   * Verifies that authenticating with valid standard user credentials successfully transitions
   * to the main application scene and displays expected customer action controls.
   */
  @Test
  @DisplayName("Should successfully authenticate standard user and transition to MAIN scene")
  public void testSuccessfulUserLogin() {
    clickOn("#usernameField").eraseText(20).write("john_doe");
    clickOn("#passwordField").eraseText(20).write("Password123!");
    clickOn("#loginButton");

    // Verify MAIN scene title appears
    verifyThat("Welcome to Cache Me Outside Clothing Co.", NodeMatchers.isVisible());

    // Verify user options exist
    verifyThat("Shopping Cart", NodeMatchers.isVisible());
    verifyThat("Browse Product", NodeMatchers.isVisible());
  }

  /**
   * Verifies that authenticating with valid administrative credentials successfully transitions
   * to the main scene and renders elevated admin management UI components.
   */
  @Test
  @DisplayName("Should successfully authenticate ADMIN user and display elevated action controls")
  public void testSuccessfulAdminLogin() {
    clickOn("#usernameField").write("admin_user");
    clickOn("#passwordField").write("AdminPass123!");
    clickOn("#loginButton");

    // Verify MAIN scene title appears
    verifyThat("Welcome to Cache Me Outside Clothing Co.", NodeMatchers.isVisible());

    // Verify ADMIN controls exist
    verifyThat("Admin Todo List", NodeMatchers.isVisible());
    verifyThat("Admin User Dashboard", NodeMatchers.isVisible());
    verifyThat("Catalog Management", NodeMatchers.isVisible());
  }


  /**
   * Verifies that clicking the password recovery hyperlink triggers scene navigation
   * to the Password Reset screen.
   */
  @Test
  @DisplayName("Should navigate to Password Reset scene when 'Forgot password?' is clicked")
  public void testForgotPasswordNavigation() {
    clickOn("Forgot password?");
    verifyThat("Reset Password", NodeMatchers.isVisible());
  }
}