import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for the {@link UserDAO} class.
 * <p>
 * Validates database operations including user retrieval, role lookups,
 * security question queries, password updates, and security answer verification.
 * Tests are executed against an isolated in-memory SQLite database to ensure clean,
 * repeatable test runs without side effects on production data.
 * </p>
 *
 * @author Miguel Quezada
 * @version 0.1.0
 * @since 2026-08-13
 *
 *  These tests were generated by Courtesy of Claude from Anthropic.
 *  Prompt Used:
 *  I have these code files ( submitted the code )
 *  src/main/java/DatabaseManager.java
 *  src/main/java/UserInfo.java
 *  src/main/java/UserDAO.java
 *
 *  Write DAO unit tests for user retrieval and password updates.
 *  The tests will live in this folder in my project
 *  src/test/java/
 *
 */
public class UserDAOTest {

  private Connection connection;
  private DatabaseManager dbManager;
  private UserDAO userDAO;

  /**
   * Sets up an in-memory SQLite database connection and initializes the schema
   * prior to running each test. Pre-populates the database with initial standard
   * and admin user records.
   *
   * @throws SQLException if a database access or initialization error occurs
   */
  @BeforeEach
  public void setUp() throws SQLException {
    // Establish an isolated in-memory SQLite connection for testing
    connection = DriverManager.getConnection("jdbc:sqlite::memory:");

    // Initialize schema using the existing DatabaseManager test constructor
    dbManager = new DatabaseManager(connection, true);
    userDAO = dbManager.getUserDAO();

    // Seed initial data for testing
    userDAO.registerUser(
        "johndoe",
        "Password123!",
        "johndoe@example.com",
        "John",
        "Doe",
        "555-0199",
        "123 Main St",
        "Fresno",
        "CA",
        "93720",
        "USER",
        "What is your pet's name?",
        "Fluffy"
    );

    userDAO.registerUser(
        "adminuser",
        "AdminPass123!",
        "admin@example.com",
        "Alice",
        "Admin",
        "555-0100",
        "456 Oak Rd",
        "Clovis",
        "CA",
        "93611",
        "ADMIN",
        "What city were you born in?",
        "Fresno"
    );
  }

  /**
   * Closes the in-memory database connection after each test execution to free resources
   * and reset state.
   */
  @AfterEach
  public void tearDown() {
    if (dbManager != null) {
      dbManager.close();
    }
  }

  // -----------------------------
  // USER RETRIEVAL TESTS
  // -----------------------------

  /**
   * Tests that {@link UserDAO#getAllUsersForAdmin()} retrieves all registered users
   * ordered by user ID and correctly populates fields including usernames, emails, and roles.
   */
  @Test
  @DisplayName("getAllUsersForAdmin should return all registered users with mapped roles")
  public void testGetAllUsersForAdmin() {
    List<UserInfo> users = userDAO.getAllUsersForAdmin();

    assertNotNull(users, "User list should not be null.");
    assertEquals(2, users.size(), "User list should contain exactly 2 registered users.");

    UserInfo user1 = users.get(0);
    assertEquals("johndoe", user1.getUsername());
    assertEquals("johndoe@example.com", user1.getEmail());
    assertEquals("USER", user1.getRole());

    UserInfo user2 = users.get(1);
    assertEquals("adminuser", user2.getUsername());
    assertEquals("admin@example.com", user2.getEmail());
    assertEquals("ADMIN", user2.getRole());
  }

  /**
   * Tests that {@link UserDAO#getUserRole(String)} correctly retrieves the assigned role
   * for existing users and returns the default fallback role ("USER") when querying non-existent accounts.
   */
  @Test
  @DisplayName("getUserRole should return correct role for given username")
  public void testGetUserRole() {
    String roleUser = userDAO.getUserRole("johndoe");
    String roleAdmin = userDAO.getUserRole("adminuser");
    String roleNonExistent = userDAO.getUserRole("nonexistentuser");

    assertEquals("USER", roleUser);
    assertEquals("ADMIN", roleAdmin);
    // Default fallback defined in UserDAO
    assertEquals("USER", roleNonExistent);
  }

  /**
   * Tests that {@link UserDAO#getSecurityQuestion(String)} retrieves the correct security question
   * regardless of username letter casing, and returns {@code null} for unknown users.
   */
  @Test
  @DisplayName("getSecurityQuestion should retrieve correct security question case-insensitively")
  public void testGetSecurityQuestion() {
    String question = userDAO.getSecurityQuestion("JOHNdoe");
    assertNotNull(question, "Security question should be found.");
    assertEquals("What is your pet's name?", question);

    String nonExistentQuestion = userDAO.getSecurityQuestion("unknownuser");
    assertNull(nonExistentQuestion, "Non-existent user should return null question.");
  }

  // -----------------------------
  // PASSWORD UPDATE & RESET TESTS
  // -----------------------------

  /**
   * Tests that {@link UserDAO#updatePassword(String, String)} successfully updates
   * a user's password in the database, invalidating the old password and permitting
   * authentication with the newly set password.
   */
  @Test
  @DisplayName("updatePassword should correctly update hash and allow authentication with new password")
  public void testUpdatePasswordSuccess() {
    String username = "johndoe";
    String oldPassword = "Password123!";
    String newPassword = "NewSecurePassword456!";

    // Verify initial credentials
    assertTrue(userDAO.authenticateUser(username, oldPassword));

    // Update password
    boolean isUpdated = userDAO.updatePassword(username, newPassword);
    assertTrue(isUpdated, "Password update query should return true.");

    // Verify old password no longer works and new password authenticates successfully
    assertFalse(userDAO.authenticateUser(username, oldPassword), "Old password should fail authentication.");
    assertTrue(userDAO.authenticateUser(username, newPassword), "New password should pass authentication.");
  }

  /**
   * Tests that {@link UserDAO#updatePassword(String, String)} returns {@code false}
   * when attempting to update a password for a user that does not exist.
   */
  @Test
  @DisplayName("updatePassword should fail gracefully when updating non-existent user")
  public void testUpdatePasswordNonExistentUser() {
    boolean isUpdated = userDAO.updatePassword("nobody", "SomePassword123!");
    assertFalse(isUpdated, "Updating password for non-existent user should return false.");
  }

  /**
   * Tests that {@link UserDAO#verifyAndResetPassword(String, String, String)} verifies
   * the security answer case-insensitively, updates the password, and allows subsequent login
   * with the new password.
   */
  @Test
  @DisplayName("verifyAndResetPassword should succeed when security answer matches case-insensitively")
  public void testVerifyAndResetPasswordSuccess() {
    String username = "johndoe";
    String correctAnswer = "FLUFFY"; // Tests case-insensitivity against "Fluffy"
    String newPassword = "ResetPassword789!";

    boolean isReset = userDAO.verifyAndResetPassword(username, correctAnswer, newPassword);

    assertTrue(isReset, "Password reset should succeed with correct security answer.");
    assertTrue(userDAO.authenticateUser(username, newPassword), "User should authenticate with the reset password.");
  }

  /**
   * Tests that {@link UserDAO#verifyAndResetPassword(String, String, String)} fails
   * and leaves the user's password unchanged when an incorrect security answer is provided.
   */
  @Test
  @DisplayName("verifyAndResetPassword should fail when security answer is incorrect")
  public void testVerifyAndResetPasswordFailure() {
    String username = "johndoe";
    String wrongAnswer = "Fido";
    String newPassword = "ShouldNotUpdate123!";

    boolean isReset = userDAO.verifyAndResetPassword(username, wrongAnswer, newPassword);

    assertFalse(isReset, "Password reset should fail with wrong security answer.");
    assertFalse(userDAO.authenticateUser(username, newPassword), "Password should remain unchanged.");
  }
}